### PR TITLE
Update JSONMapper to v1

### PR DESCRIPTION
**Pull request by SubodhDahal**
Update JSONMapper to recent version. All the existing tests pass successfully. I also did some manual testing and everything seems to work well.

### CODE REVIEW

**Comment by hansott** [comment]
Hi! Thanks for your pull request! Highly appreciated. The build failed though: https://travis-ci.org/hansott/pinterest-php/builds/268444616, could you take a look at it? 🙇

**Comment by SubodhDahal** [comment]
Recent version of `JSONMapper` requires at least PHP 5.6 that's why it is failing on PHP versions below that. For versions 5.6 and above, the error is `InvalidArgumentException: The board id should not be empty.`. I was getting the same error on my development machine before I configured the environment variables, so I'm guessing it's because of that. Could you please check the Travis CI configuration and see if `BOARD_ID` is set?

**Comment by hansott** [comment]
Just did a reset of the board ID and restarted the build but no luck: https://travis-ci.org/hansott/pinterest-php/jobs/268444620

**Comment by turanct** [comment]
hi @SubodhDahal may I ask why the update is needed? If we merge this we'll be breaking all compatibility with older versions of PHP, and while that might be a good thing to promote the newer versions of PHP, some people might still use deprecated versions and their software will break... This PR means a major version bump for this package so it would be nice to know why we're doing this.

**Comment by SubodhDahal** [comment]
@turanct JSONMapper v1.x was already used as dependency on some of the packages I had used on my project.  Since it is not possible to use multiple versions of the same package on composer, I had to upgrade it for my package and sent a pull request as other developers might run into the same issue I did.

I found out that the recent versions of JSONMapper don't support PHP versions below 5.6, but it didn't seem much of an issue to me as 5.5 has already reached end of life and even active support time for 5.6 has already passed. Personally, I don't think we should encourage people to still be using deprecated PHP versions. Packages abandoning deprecated PHP versions might be a good incentive for many people to upgrade to newer PHP versions, like many packages are doing now. However, I do agree with you that some people might not be able to upgrade to newer versions, so I guess it will be better to bump a major version so that those people can still make use of it.

@hansott Regarding the Travis CI build, I integrated it for my fork and configured the environment variables and the builds ran without any issue. You can a look [here](https://travis-ci.org/SubodhDahal/pinterest-php) for more details.

**Comment by turanct** [comment]
@SubodhDahal i agree - if we merge this, we'll also do a major version bump

**Comment by SubodhDahal** [comment]
@turanct yeah, that sounds good

**Review by hansott — APPROVED** [review]

**Comment by hansott** [comment]
Thanks for making the required changes!

**Comment by hansott** [comment]
✅  https://travis-ci.org/hansott/pinterest-php/builds/271691705

**Pull request merged**
